---
title             : "RANKING APPLICATIONS FOR NURSERY SCHOOLS CLASSIFICATION PROBLEM"
shorttitle        : "Ranking applications for nursery schools"

author: 
  - name          : "Viviane Adohouannon"
    affiliation   : "1"
  - name          : "Kate Alexander"
    affiliation   : "1"
  - name          : "Juan Arangote"
    affiliation   : "1"
  - name          : "Dian Azbel"
    affiliation   : "1"
  - name          : "Igor Baranov"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "York University School of Continious Studies"

author_note:
  Group TFG, CSDA1010SUMA18, Lab 1 - Classification Problem

abstract:
   Nursery Database was derived from a hierarchical decision model originally developed to rank applications for nursery schools
  

bibliography      : ["r-references.bib"]

figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no
linkcolor         : "blue"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
library(readr)
library(dplyr)
library(ggplot2)
library(rpart)
library(rpart.plot)
library(Amelia)
library(rattle)
library(RColorBrewer)
library(caret)
library(papaja)
```


# Introduction
## Background
## Objective and Hypothesis
## Assessment of Situation
## Plan

# Data understanding
## Preparation
```{r}
nursery_data <- read.csv("http://archive.ics.uci.edu/ml/machine-learning-databases/nursery/nursery.data", header = FALSE, col.names = c("parents","has_nurs","form","children","housing","finance","social","health","class"))
# nursery_data <- read.csv(file = "../data/nursery_data.csv")
```
```{r ndh, results = 'asis', echo = FALSE}
apa_table(
  head(nursery_data, n = 15)
  , placement = "hp"
  , landscape = TRUE
  , small = TRUE
  , caption = "Nursery Data Header"
  , note = "This is a nursery data header"
)
```
```
```{r results='markup'}
  summary(nursery_data)
```

## Cleaning

# Feature engineering

# Modeling
## Splitting the dataset into train and test
## Decision Tree - Iteration 1
### Decision Tree model fit
### Decision Tree model evaluation

## Random Forest - Iteration 2
### Random Forest model fit
### Random Forest model evaluation

## Random Forest - Iteration 3
### Random Forest model fit
### Random Forest model evaluation

# Dicsussion

# Conclusion

\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
